### ISSUE TITLE
class Person()和class Person的区别

### ISSUE THREAD

**Issue by smartczy** [qiwsir/ITArticles#23]
类在需要继承的时候需要加括号，可是在不需要继承的时候，我看到有些地方也加括号，形如
```python
class Person():
```
所以想问下class Person和class Person()之间有没有区别

**Comment by qiwsir** [comment]
其实，我在这个版本里面这么写不是很好。因为在python2里面，有新式类和旧式类之分。在python3中，没有这个区别，或者说都是新式类。python2中的新旧之别，是因为历史造成的。我在教程中，没有很好的区分和明确指出。这是我在第二版中会改正的部分。

**Comment by smartczy** [comment]
所以说，在python2里二者没有区别了是嘛？

**Comment by qiwsir** [comment]
是python3里面没必要做这种区别。但是，目前我建议还是要学python2。详情请阅读我的教程https://github.com/qiwsir/StarterLearningPython/blob/master/03.md的末尾说明

**Comment by smartczy** [comment]
从您的回答里，我知道python3里class Person():和class Person:是没有必要区别的。
不好意思，可是我觉得您还是没回答我的问题：我现在用的python2，在python2里，加括号与不加括号到底有没有区别？还是说加不加括号没有影响？如果没有区别，您建议使用哪种？

**Comment by qiwsir** [comment]
第一版在这里写的不好。请看我第二版。刚刚发布的。做了很大幅度的修改：https://github.com/qiwsir/StarterLearningPython/blob/master/207.md
