### ISSUE TITLE
准备把你的几篇文章收入：https://github.com/justjavac/free-programming-books-zh_CN

### ISSUE THREAD

**Issue by justjavac** [qiwsir/ITArticles#9]
准备把你的几篇文章收入：https://github.com/justjavac/free-programming-books-zh_CN

**Comment by qiwsir** [comment]
如果是我原创，只要注明网址和作者即可。如果是我转载别人的，也请注明原始网址和作者。谢谢

2015-09-02 15:44 GMT+08:00 迷渡 <notifications@github.com>:

> Closed #9 <https://github.com/qiwsir/ITArticles/issues/9>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qiwsir/ITArticles/issues/9#event-398624079>.
>



-- 
*QiWei*

**Comment by justjavac** [comment]
@qiwsir 你我索引你这个 repo

**Comment by qiwsir** [comment]
已经看到。可以。谢谢。
